name: GitHub Actions After Push Into Develop Branch
on:
  push:
    branches:
      - ibrahim
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: 1036826
      - run: chrome --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
           node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run wdio-chrome 
