name: Checkout
on: [pull_request, workflow_dispatch]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - run: ls -a
      - uses: actions/checkout@v3
      - run: ls -a
      - run: |
          date > generated.txt
          git add .
          git commit -m "generated"
          git push
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: |
          pwd
          ls -a